In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("car.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [3]:
print(x)

[['vhigh' 'vhigh' '2' '2' 'small' 'low']
 ['vhigh' 'vhigh' '2' '2' 'small' 'med']
 ['vhigh' 'vhigh' '2' '2' 'small' 'high']
 ...
 ['low' 'low' '5more' 'more' 'big' 'low']
 ['low' 'low' '5more' 'more' 'big' 'med']
 ['low' 'low' '5more' 'more' 'big' 'high']]


In [4]:
print(y)

['unacc' 'unacc' 'unacc' ... 'unacc' 'good' 'vgood']


In [5]:
data.isnull().sum()

buying        0
maint         0
doors         0
persons       0
lug_boot      0
safety        0
Unnamed: 6    0
dtype: int64

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

[[0.0 0.0 0.0 ... '2' 'small' 'low']
 [0.0 0.0 0.0 ... '2' 'small' 'med']
 [0.0 0.0 0.0 ... '2' 'small' 'high']
 ...
 [0.0 1.0 0.0 ... 'more' 'big' 'low']
 [0.0 1.0 0.0 ... 'more' 'big' 'med']
 [0.0 1.0 0.0 ... 'more' 'big' 'high']]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
print (y)

[2 2 2 ... 2 1 3]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [11]:
print(x_train)

[[0.0 1.0 0.0 ... '4' 'med' 'med']
 [1.0 0.0 0.0 ... '4' 'med' 'med']
 [0.0 0.0 0.0 ... '2' 'small' 'high']
 ...
 [0.0 0.0 1.0 ... '4' 'big' 'med']
 [0.0 0.0 0.0 ... 'more' 'small' 'med']
 [0.0 0.0 1.0 ... '2' 'big' 'high']]


In [12]:
print(x_test)

[[0.0 0.0 1.0 ... 'more' 'small' 'low']
 [1.0 0.0 0.0 ... 'more' 'big' 'med']
 [1.0 0.0 0.0 ... '2' 'med' 'med']
 ...
 [0.0 0.0 0.0 ... '2' 'big' 'high']
 [0.0 0.0 0.0 ... 'more' 'med' 'med']
 [0.0 0.0 0.0 ... '4' 'med' 'med']]


In [13]:
print(y_train)

[1 0 2 ... 0 2 2]


In [14]:
print(y_test)

[2 0 2 2 2 0 2 2 0 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 3 2 2 2 2 2 2
 2 0 2 2 0 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 3 2 1 2 2 2 2 0 2 2 2 2 2
 1 2 2 0 0 0 0 0 1 2 2 3 0 2 0 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2
 0 2 2 0 0 2 1 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 3 2 2 3 2 2 2 2 0 0 2 0 2 0
 2 2 2 2 2 2 1 0 0 2 2 2 2 2 0 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 1 2 2 2 2 0 2 2 3 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 3 0 0 2 0 2 3 2 2 2 2 2 2
 2 0 2 2 2 2 2 2 0 2 2 2 1 0 2 2 0 2 2 2 0 1 2 0 2 0 2 2 2 2 1 2 2 0 0 2 2
 2 2 2 2 0 2 2 2 1 2 2 2 0 1 2 2 2 0 2 2 1 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2
 2 3 2 2 2 2 2 2 2 0 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 3 0 0 2 0 0 2 2 0 1 2
 2 2 2 0 2 2 0 0 2 3 2 2 2]


In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train[:, :4])
scaled_x_test = sc.transform(x_test[:, :4])

In [28]:
print (scaled_x_train)

[[-0.58682023  1.74722235 -0.57790729 -0.572337  ]
 [ 1.70409941 -0.572337   -0.57790729 -0.572337  ]
 [-0.58682023 -0.572337   -0.57790729  1.74722235]
 ...
 [-0.58682023 -0.572337    1.73038136 -0.572337  ]
 [-0.58682023 -0.572337   -0.57790729  1.74722235]
 [-0.58682023 -0.572337    1.73038136 -0.572337  ]]


In [29]:
print (scaled_x_test)

[[-0.58682023 -0.572337    1.73038136 -0.572337  ]
 [ 1.70409941 -0.572337   -0.57790729 -0.572337  ]
 [ 1.70409941 -0.572337   -0.57790729 -0.572337  ]
 ...
 [-0.58682023 -0.572337   -0.57790729  1.74722235]
 [-0.58682023 -0.572337   -0.57790729  1.74722235]
 [-0.58682023 -0.572337   -0.57790729  1.74722235]]
